import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./_components/Navbar/Navbar";
import Footer from "./_components/Footer/Footer";   
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter'; 

import { Roboto } from 'next/font/google';
import { ThemeProvider } from '@mui/material/styles';
import theme from '../theme';
import { Box } from "@mui/material";

const roboto = Roboto({
  weight: ['300', '400', '500', '700'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-roboto',
});




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.variable} style={{margin:0}}>
      <AppRouterCacheProvider>
      <ThemeProvider theme={theme}>
      <Navbar/>
     <Box padding={5}>
        {children}
     </Box>
      
      <Footer/>
      </ThemeProvider>
      </AppRouterCacheProvider>
       
      </body>
    </html>
  );
}
